
#
# Build Workflow
#

name: Build-Windows

run-name: ${{ github.actor }} started a windows build.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Build System
        run: cmake -S . -B build -G"Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: cmake --build build --config Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-windows
          path: build/builds/release/